server:
  http:
    addr: 0.0.0.0:6080
    timeout: 1s
  grpc:
    addr: 0.0.0.0:6001
    timeout: 1s

machine_id: 1 # 机器ID，用于生成唯一ID

data:
  database:
    addr: 192.168.5.51:3306
    user: root
    password: "123456"
    database: shorturlx
    max_idle_conn : 100
    max_open_conn: 150
    max_idle_time: 30
    slow_threshold_millisecond: 10 # SQL执行超过10ms，就算慢sql

  redis:
    addr: 192.168.5.52:6379
    password: "123456"
    db: 6
    pool_size: 20
    bloom_filter_size: 1000000 # 布隆过滤器大小
    error_rate: 0.01 # 布隆过滤器错误率
    read_timeout: 2s
    write_timeout: 2s

micro:
  lb:
    addr: 127.0.0.1:2379

log:
  level: info
  log_path: ./log
  max_size: 100 # 日志保留大小，以 M 为单位
  max_backups: 3 # 保留文件个数
  console: true # false为不打印到终端
  filename: shortUrlx.log



